import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/supabaseClient';

// Mock quiz data for development (until database is seeded)
const MOCK_QUIZZES: Record<string, any> = {
  'survey-30days': {
    id: 'survey-30days',
    title: '30-Day Follow-Up Survey',
    description: 'Track your progress 30 days after course completion',
    estimated_time: 8,
    questions: [
      {
        id: 'q1',
        type: 'multiple-choice',
        question: 'How would you rate your overall course experience?',
        options: ['Excellent', 'Good', 'Fair', 'Poor'],
        required: true,
      },
      {
        id: 'q2',
        type: 'rating',
        question: 'How confident do you feel in applying what you learned?',
        min: 1,
        max: 5,
        minLabel: 'Not confident',
        maxLabel: 'Very confident',
        required: true,
      },
      {
        id: 'q3',
        type: 'multiple-choice',
        question: 'Have you started applying the skills from the course?',
        options: ['Yes, extensively', 'Yes, somewhat', 'Not yet', 'Not planning to'],
        required: true,
      },
      {
        id: 'q4',
        type: 'checkbox',
        question: 'Which topics from the course have you used? (Select all that apply)',
        options: [
          'Machine Learning Basics',
          'Neural Networks',
          'Data Preprocessing',
          'Model Evaluation',
          'Deployment Strategies',
          'None yet',
        ],
        required: false,
      },
      {
        id: 'q5',
        type: 'text-long',
        question: 'What has been the most valuable skill or concept you learned?',
        required: true,
      },
      {
        id: 'q6',
        type: 'rating',
        question: 'How relevant was the course content to your career goals?',
        min: 1,
        max: 5,
        minLabel: 'Not relevant',
        maxLabel: 'Very relevant',
        required: true,
      },
      {
        id: 'q7',
        type: 'multiple-choice',
        question: 'Are you currently employed in a role related to AI/ML?',
        options: [
          'Yes, full-time',
          'Yes, part-time',
          'No, but actively searching',
          'No, not currently seeking',
        ],
        required: true,
      },
      {
        id: 'q8',
        type: 'text-short',
        question: 'What is your current job title or desired role?',
        required: false,
      },
      {
        id: 'q9',
        type: 'rating',
        question: 'How likely are you to recommend this course to others?',
        min: 0,
        max: 10,
        minLabel: 'Not likely',
        maxLabel: 'Very likely',
        required: true,
      },
      {
        id: 'q10',
        type: 'checkbox',
        question: 'What challenges have you faced while applying your new skills?',
        options: [
          'Limited job opportunities',
          'Lack of hands-on experience',
          'Need more advanced training',
          'Difficulty finding projects',
          'Imposter syndrome',
          'None',
        ],
        required: false,
      },
      {
        id: 'q11',
        type: 'text-long',
        question: 'What additional support or resources would help you succeed?',
        required: false,
      },
      {
        id: 'q12',
        type: 'multiple-choice',
        question: 'Have you worked on any AI/ML projects since completing the course?',
        options: [
          'Yes, professional projects',
          'Yes, personal projects',
          'No, but planning to',
          'No, not yet',
        ],
        required: true,
      },
      {
        id: 'q13',
        type: 'rating',
        question: 'How well did the course prepare you for real-world applications?',
        min: 1,
        max: 5,
        minLabel: 'Not well',
        maxLabel: 'Very well',
        required: true,
      },
      {
        id: 'q14',
        type: 'text-short',
        question: 'What is one thing you wish the course had covered in more depth?',
        required: false,
      },
      {
        id: 'q15',
        type: 'multiple-choice',
        question: 'Are you pursuing additional AI/ML education or certifications?',
        options: [
          'Yes, currently enrolled',
          'Yes, planning to',
          'No, but interested',
          'No, not interested',
        ],
        required: true,
      },
      {
        id: 'q16',
        type: 'checkbox',
        question: 'What areas of AI/ML are you most interested in exploring further?',
        options: [
          'Deep Learning',
          'Natural Language Processing',
          'Computer Vision',
          'Reinforcement Learning',
          'MLOps',
          'Other',
        ],
        required: false,
      },
      {
        id: 'q17',
        type: 'text-long',
        question: 'Any additional feedback or suggestions for improving the course?',
        required: false,
      },
    ],
  },
  'survey-90days': {
    id: 'survey-90days',
    title: '90-Day Progress Check-In',
    description: 'Assess your career progress and job search status',
    estimated_time: 12,
    questions: [
      {
        id: 'q1',
        type: 'multiple-choice',
        question: 'What is your current employment status?',
        options: [
          'Employed in AI/ML role',
          'Employed in related technical role',
          'Actively job searching',
          'Not currently seeking employment',
        ],
        required: true,
      },
      {
        id: 'q2',
        type: 'text-short',
        question: 'What is your current job title?',
        required: false,
      },
      {
        id: 'q3',
        type: 'rating',
        question: 'How satisfied are you with your career progress since the course?',
        min: 1,
        max: 5,
        minLabel: 'Not satisfied',
        maxLabel: 'Very satisfied',
        required: true,
      },
      {
        id: 'q4',
        type: 'multiple-choice',
        question: 'Have you received any job offers related to AI/ML?',
        options: [
          'Yes, accepted',
          'Yes, but declined',
          'Yes, still considering',
          'No, but interviewing',
          'No, still searching',
        ],
        required: true,
      },
      {
        id: 'q5',
        type: 'number',
        question: 'How many AI/ML related job applications have you submitted?',
        min: 0,
        max: 500,
        required: false,
      },
      {
        id: 'q6',
        type: 'number',
        question: 'How many interviews have you had for AI/ML positions?',
        min: 0,
        max: 100,
        required: false,
      },
      {
        id: 'q7',
        type: 'checkbox',
        question: 'What job search resources are you using? (Select all that apply)',
        options: [
          'LinkedIn',
          'Indeed',
          'Company websites',
          'Networking events',
          'Recruitment agencies',
          'Alumni network',
          'Other',
        ],
        required: false,
      },
      {
        id: 'q8',
        type: 'rating',
        question: 'How confident are you in your technical interview skills?',
        min: 1,
        max: 5,
        minLabel: 'Not confident',
        maxLabel: 'Very confident',
        required: true,
      },
      {
        id: 'q9',
        type: 'multiple-choice',
        question: 'Have you built a portfolio of AI/ML projects?',
        options: [
          'Yes, comprehensive portfolio',
          'Yes, a few projects',
          'Working on it',
          'Not yet started',
        ],
        required: true,
      },
      {
        id: 'q10',
        type: 'text-short',
        question: 'What is your target salary range for AI/ML roles?',
        required: false,
      },
      {
        id: 'q11',
        type: 'checkbox',
        question: 'What skills are employers asking for in job postings you see?',
        options: [
          'Python',
          'TensorFlow/PyTorch',
          'Cloud platforms (AWS/Azure/GCP)',
          'SQL/Databases',
          'Docker/Kubernetes',
          'Communication skills',
          'Domain expertise',
        ],
        required: false,
      },
      {
        id: 'q12',
        type: 'rating',
        question: 'How well do you feel your skills match current job requirements?',
        min: 1,
        max: 5,
        minLabel: 'Poor match',
        maxLabel: 'Excellent match',
        required: true,
      },
      {
        id: 'q13',
        type: 'text-long',
        question: 'What has been your biggest challenge in the job search process?',
        required: true,
      },
      {
        id: 'q14',
        type: 'multiple-choice',
        question: 'Are you open to relocating for the right opportunity?',
        options: ['Yes, anywhere', 'Yes, within my country', 'Only locally', 'Prefer remote only'],
        required: true,
      },
      {
        id: 'q15',
        type: 'checkbox',
        question: 'What type of companies are you targeting?',
        options: [
          'Tech giants (FAANG)',
          'Startups',
          'Medium-sized tech companies',
          'Non-tech companies with AI teams',
          'Consulting firms',
          'Research institutions',
        ],
        required: false,
      },
      {
        id: 'q16',
        type: 'rating',
        question: 'How active are you in the AI/ML community (meetups, forums, etc.)?',
        min: 1,
        max: 5,
        minLabel: 'Not active',
        maxLabel: 'Very active',
        required: true,
      },
      {
        id: 'q17',
        type: 'text-long',
        question: 'What strategies have been most effective in your job search?',
        required: false,
      },
      {
        id: 'q18',
        type: 'multiple-choice',
        question: 'Have you received any promotions or raises since completing the course?',
        options: [
          'Yes, promotion',
          'Yes, raise',
          'Yes, both',
          'No, but expecting soon',
          'No',
        ],
        required: false,
      },
      {
        id: 'q19',
        type: 'checkbox',
        question: 'What additional certifications or courses have you completed?',
        options: [
          'AWS Certified Machine Learning',
          'Google Cloud Professional ML Engineer',
          'Deep Learning Specialization',
          'Azure AI Engineer',
          'TensorFlow Developer Certificate',
          'None yet',
        ],
        required: false,
      },
      {
        id: 'q20',
        type: 'rating',
        question: 'How optimistic are you about landing your ideal AI/ML role?',
        min: 1,
        max: 5,
        minLabel: 'Not optimistic',
        maxLabel: 'Very optimistic',
        required: true,
      },
      {
        id: 'q21',
        type: 'text-short',
        question: 'What is your ideal job title or role?',
        required: false,
      },
      {
        id: 'q22',
        type: 'multiple-choice',
        question: 'Are you considering freelancing or consulting in AI/ML?',
        options: [
          'Yes, already doing it',
          'Yes, planning to start',
          'Maybe, exploring options',
          'No, prefer full-time employment',
        ],
        required: false,
      },
      {
        id: 'q23',
        type: 'text-long',
        question: 'What project or achievement are you most proud of since the course?',
        required: false,
      },
      {
        id: 'q24',
        type: 'checkbox',
        question: 'What barriers are preventing you from getting your desired role?',
        options: [
          'Lack of experience',
          'Geographic location',
          'Salary expectations',
          'Limited job openings',
          'Technical skill gaps',
          'Interview performance',
          'None',
        ],
        required: false,
      },
      {
        id: 'q25',
        type: 'rating',
        question: 'How valuable has your professional network been in your job search?',
        min: 1,
        max: 5,
        minLabel: 'Not valuable',
        maxLabel: 'Very valuable',
        required: true,
      },
      {
        id: 'q26',
        type: 'text-short',
        question: 'How many connections have you made in the AI/ML community?',
        required: false,
      },
      {
        id: 'q27',
        type: 'multiple-choice',
        question: 'Are you contributing to open-source AI/ML projects?',
        options: [
          'Yes, actively',
          'Yes, occasionally',
          'Planning to start',
          'No, not interested',
        ],
        required: false,
      },
      {
        id: 'q28',
        type: 'rating',
        question: 'How well has the course alumni network supported your career goals?',
        min: 1,
        max: 5,
        minLabel: 'Not at all',
        maxLabel: 'Very well',
        required: true,
      },
      {
        id: 'q29',
        type: 'text-long',
        question:
          'What advice would you give to someone just starting their AI/ML career journey?',
        required: false,
      },
    ],
  },
  'survey-180days': {
    id: 'survey-180days',
    title: '6-Month Impact Assessment',
    description: 'Measure long-term career progression and skill application',
    estimated_time: 15,
    questions: [
      {
        id: 'q1',
        type: 'rating',
        question: 'How confident are you in your AI/ML skills now?',
        min: 1,
        max: 5,
        minLabel: 'Not confident',
        maxLabel: 'Very confident',
        required: true,
      },
      {
        id: 'q2',
        type: 'multiple-choice',
        question: 'What is your current employment situation?',
        options: [
          'Working in AI/ML role',
          'Working in tech, applying AI/ML',
          'Working in non-tech role',
          'Between jobs',
          'Student/further education',
        ],
        required: true,
      },
      {
        id: 'q3',
        type: 'text-short',
        question: 'Current job title (if employed)',
        required: false,
      },
      {
        id: 'q4',
        type: 'number',
        question: 'Current annual salary (or salary offer if recently hired)',
        min: 0,
        max: 500000,
        required: false,
      },
      {
        id: 'q5',
        type: 'rating',
        question: 'How has your income changed since starting the course?',
        min: 1,
        max: 5,
        minLabel: 'Decreased significantly',
        maxLabel: 'Increased significantly',
        required: true,
      },
      {
        id: 'q6',
        type: 'checkbox',
        question: 'Which AI/ML technologies do you use regularly in your work?',
        options: [
          'Python/Scikit-learn',
          'TensorFlow',
          'PyTorch',
          'Keras',
          'Hugging Face',
          'LangChain',
          'MLflow',
          'Kubernetes',
          'None yet',
        ],
        required: false,
      },
      {
        id: 'q7',
        type: 'number',
        question: 'How many AI/ML projects have you completed professionally?',
        min: 0,
        max: 100,
        required: false,
      },
      {
        id: 'q8',
        type: 'text-long',
        question: 'Describe the most impactful AI/ML project you have worked on',
        required: false,
      },
      {
        id: 'q9',
        type: 'rating',
        question: 'How would you rate your career satisfaction now?',
        min: 1,
        max: 5,
        minLabel: 'Very dissatisfied',
        maxLabel: 'Very satisfied',
        required: true,
      },
      {
        id: 'q10',
        type: 'multiple-choice',
        question: 'Have you been promoted or changed roles since the course?',
        options: [
          'Yes, promoted in current company',
          'Yes, moved to a better role elsewhere',
          'No, but on track for promotion',
          'No change yet',
        ],
        required: true,
      },
      {
        id: 'q11',
        type: 'checkbox',
        question: 'What areas of AI/ML are you actively working with?',
        options: [
          'Natural Language Processing',
          'Computer Vision',
          'Recommender Systems',
          'Time Series Analysis',
          'Reinforcement Learning',
          'Generative AI',
          'MLOps',
        ],
        required: false,
      },
      {
        id: 'q12',
        type: 'rating',
        question: 'How well are you applying course concepts in real-world scenarios?',
        min: 1,
        max: 5,
        minLabel: 'Not applying',
        maxLabel: 'Extensively applying',
        required: true,
      },
      {
        id: 'q13',
        type: 'text-long',
        question: 'What skills have proven most valuable in your current role?',
        required: true,
      },
      {
        id: 'q14',
        type: 'multiple-choice',
        question: 'Are you mentoring others in AI/ML?',
        options: [
          'Yes, formally',
          'Yes, informally',
          'Planning to start',
          'Not currently',
        ],
        required: false,
      },
      {
        id: 'q15',
        type: 'rating',
        question: 'How valuable has the course been for your long-term career?',
        min: 1,
        max: 5,
        minLabel: 'Not valuable',
        maxLabel: 'Extremely valuable',
        required: true,
      },
      {
        id: 'q16',
        type: 'text-long',
        question: 'What unexpected opportunities has your AI/ML knowledge created?',
        required: false,
      },
    ],
  },
  'survey-12months-final': {
    id: 'survey-12months-final',
    title: '12-Month Final Assessment',
    description: 'Comprehensive evaluation of your career transformation',
    estimated_time: 10,
    questions: [
      {
        id: 'q1',
        type: 'text-long',
        question: 'Describe your career transformation over the past year',
        required: true,
      },
      {
        id: 'q2',
        type: 'rating',
        question: 'Overall, how would you rate your career progress this year?',
        min: 1,
        max: 5,
        minLabel: 'No progress',
        maxLabel: 'Exceptional progress',
        required: true,
      },
      {
        id: 'q3',
        type: 'multiple-choice',
        question: 'What is your current professional status?',
        options: [
          'Senior AI/ML role',
          'Mid-level AI/ML role',
          'Entry-level AI/ML role',
          'Non-AI/ML role using AI skills',
          'Transitioning careers',
          'Independent consultant/freelancer',
        ],
        required: true,
      },
      {
        id: 'q4',
        type: 'text-short',
        question: 'Current job title and company (optional)',
        required: false,
      },
      {
        id: 'q5',
        type: 'number',
        question: 'Salary increase percentage since starting the course (if applicable)',
        min: -100,
        max: 500,
        required: false,
      },
      {
        id: 'q6',
        type: 'rating',
        question: 'How satisfied are you with your current career trajectory?',
        min: 1,
        max: 5,
        minLabel: 'Very dissatisfied',
        maxLabel: 'Very satisfied',
        required: true,
      },
      {
        id: 'q7',
        type: 'checkbox',
        question: 'What major achievements have you accomplished this year?',
        options: [
          'Landed dream job',
          'Got promoted',
          'Significant salary increase',
          'Published research/articles',
          'Spoke at conferences',
          'Launched personal projects',
          'Contributed to open source',
          'Built professional network',
        ],
        required: false,
      },
      {
        id: 'q8',
        type: 'text-long',
        question: 'What has been your proudest professional achievement this year?',
        required: true,
      },
      {
        id: 'q9',
        type: 'rating',
        question: 'How much has the course impacted your overall career success?',
        min: 1,
        max: 5,
        minLabel: 'No impact',
        maxLabel: 'Transformative impact',
        required: true,
      },
      {
        id: 'q10',
        type: 'multiple-choice',
        question: 'Would you recommend this course to others pursuing AI/ML careers?',
        options: [
          'Absolutely, without reservation',
          'Yes, with some caveats',
          'Maybe, depends on their goals',
          'Probably not',
          'Definitely not',
        ],
        required: true,
      },
      {
        id: 'q11',
        type: 'text-long',
        question: 'What advice would you give to future students of this course?',
        required: true,
      },
      {
        id: 'q12',
        type: 'checkbox',
        question: 'What skills from the course do you use most frequently?',
        options: [
          'Machine learning fundamentals',
          'Deep learning',
          'Data preprocessing',
          'Model deployment',
          'Python programming',
          'Statistical analysis',
          'Problem-solving approach',
          'Project management',
        ],
        required: false,
      },
      {
        id: 'q13',
        type: 'rating',
        question: 'How confident are you in mentoring others in AI/ML now?',
        min: 1,
        max: 5,
        minLabel: 'Not confident',
        maxLabel: 'Very confident',
        required: true,
      },
      {
        id: 'q14',
        type: 'text-long',
        question: 'What additional support or resources would have enhanced your success?',
        required: false,
      },
      {
        id: 'q15',
        type: 'multiple-choice',
        question: 'What are your career plans for the next year?',
        options: [
          'Continue growing in current role',
          'Seek senior/leadership position',
          'Start own AI/ML business',
          'Pivot to specialized AI domain',
          'Pursue advanced degree',
          'Other',
        ],
        required: true,
      },
      {
        id: 'q16',
        type: 'rating',
        question: 'How likely are you to continue learning and developing AI/ML skills?',
        min: 1,
        max: 5,
        minLabel: 'Not likely',
        maxLabel: 'Extremely likely',
        required: true,
      },
      {
        id: 'q17',
        type: 'text-long',
        question: 'What impact has your AI/ML work had on your organization or clients?',
        required: false,
      },
      {
        id: 'q18',
        type: 'checkbox',
        question: 'What challenges did you overcome this year?',
        options: [
          'Imposter syndrome',
          'Technical skill gaps',
          'Work-life balance',
          'Job market competition',
          'Salary negotiations',
          'Career direction uncertainty',
          'Team collaboration',
        ],
        required: false,
      },
      {
        id: 'q19',
        type: 'rating',
        question: 'How well has the course alumni network supported your journey?',
        min: 1,
        max: 5,
        minLabel: 'Not helpful',
        maxLabel: 'Extremely helpful',
        required: true,
      },
      {
        id: 'q20',
        type: 'text-long',
        question: 'What has been the most surprising aspect of your AI/ML career journey?',
        required: false,
      },
      {
        id: 'q21',
        type: 'text-long',
        question:
          'Final thoughts: Is there anything else you would like to share about your experience?',
        required: false,
      },
    ],
  },
};

export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;

    if (!id) {
      return NextResponse.json({ error: 'Quiz ID is required' }, { status: 400 });
    }

    // Check if mock quiz exists first (for development)
    const mockQuiz = MOCK_QUIZZES[id];
    if (mockQuiz) {
      return NextResponse.json({ quiz: mockQuiz }, { status: 200 });
    }

    // Try to get quiz from database (for production with real UUIDs)
    const { data, error } = await db.getQuiz(id);

    // If quiz exists in database, use it
    if (data && !error) {
      const quizData = data as any;
      const quiz = {
        id: quizData.id,
        title: quizData.title,
        description: quizData.description,
        questions: quizData.questions,
        estimatedTime: quizData.estimated_time,
        createdAt: quizData.created_at,
        updatedAt: quizData.updated_at,
      };

      return NextResponse.json({ quiz }, { status: 200 });
    }

    // Not found in either mock data or database
    return NextResponse.json({ error: 'Quiz not found' }, { status: 404 });
  } catch (error) {
    console.error('Unexpected error in GET /api/quiz/[id]:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
